### ISSUE TITLE
Error log output.

### ISSUE THREAD

**Issue by MyGamesStore** [CE-PhoenixCart/PhoenixCart#11]
Stock install produces this error in log occasionally.

AH01071: Got error 'PHP message: PHP Notice:  Undefined index: manufacturers_seo_title in /includes/classes/manufacturer.php on line 27PHP message: PHP Notice:  Undefined index: manufacturers_name in /includes/classes/manufacturer.php on line 27PHP message: PHP Notice:  Undefined index: manufacturers_name in /includes/classes/manufacturer.php on line 27PHP message: PHP Notice:  Undefined index: manufacturers_image in /includes/classes/manufacturer.php on line 27PHP message: PHP Notice:  Undefined index: manufacturers_description in /includes/classes/manufacturer.php on line 27'

**Comment by ecartz** [comment]
This is the kind of thing that you'd see if an invalid manufacturer is requested.  You'd have to do more troubleshooting to see what causes this and under what circumstances before someone could work on it.  If you need help with that and are not in position to hire one of the certified developers to troubleshoot, you might try posting in the forum for more help.
