### ISSUE TITLE
IS_PRODUCT_SHOW_PRICE  IS_PRODUCT_BUTTON_VIEW

### ISSUE THREAD

**Issue by MyGamesStore** [CE-PhoenixCart/PhoenixCart#13]
On stock install, If you remove all the Box modules, the Price and View buttons on the New Products panel on the Index page are replaced on the _first listed product_ with  text listed above.

Turning back on any of  Reviews, Specials or Whats new box modules restores the price and view button graphic.

Sadly I dont want any boxes, so this becomes an issue.

**Comment by gburton** [comment]
Seems to hinge on the "Whats New" box.  If that is removed, this effect can be seen.

**Comment by ecartz** [comment]
If anyone just wants to hack it to make this problem go away, I'm pretty sure that it's sufficient to move the attribute line to the beginning of the loop.  So they look like 

```
    while ($card_products = tep_db_fetch_array($card_products_query)) {
        $has_attributes = (tep_has_product_attributes((int)$card_products['products_id']) === true) ? '1' : '0';
```

No new lines.  That just moves one line (the second) higher in the file.  That line is why the second and later products work.  It will be fixed as part of a larger set of changes in the next release.
