### ISSUE TITLE
translation of installation

### ISSUE THREAD

**Issue by cupidare** [CE-PhoenixCart/PhoenixCart#14]
Good evening, 

I could contribute the german translation of the installation files. The could be found here 

https://github.com/cupidare/PhoenixCart-German-Language/tree/master/install/includes/translations/de

or shall I create a PR? Is it intended to place them into core?

Thank you

**Comment by ecartz** [comment]
No, it's the same as always.  Just put it in https://phoenixcart.org/forum/app.php/addons/free_addon/german_language_deutsches_sprachpaket/

The installation translation is a drop-in (it does not need installed).  So adding it is as simple as dropping it into the correct place.  At the moment, this just saves having to translate the install in place.  It's not meant to attempt a multilingual install in general.  Someone would still have to copy the language files manually.  

It might be possible to use [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to create a PhoenixCart-Deutsch distribution that pulls files from both CE-PhoenixCart/PhoenixCart and cupidare/PhoenixCart-German-Language

There's probably still more work needed.  For example, I think that post-installation, it would go back to defaulting to English until someone manually installed German in admin.  But I'm probably not going to do anything more with that in the 1.0.8.* series.
