### ISSUE TITLE
Link on the main website points to the wrong repository

### ISSUE THREAD

**Issue by chrisjlocke** [CE-PhoenixCart/PhoenixCart#2]
When I go to https://phoenixcart.org/download_ce_phoenix.php, the big download button points to https://github.com/CE-PhoenixCart/Phoenix/archive/master.zip which returns a big fat 404.  Well, actually, a small 'Not Found', which isn't helpful.
Its the wrong repository, as it should point to https://github.com/CE-PhoenixCart/**PhoenixCart**/archive/master.zip (obviously without the stars, but just highlighting where the issue is... thought it might make it bold...)

Anyway.
Using Softaculous to install PhoenixCart also failed miserably, but that might be due to a hosting issue.  Was losing the will to live with so many issues... :(

**Comment by heatherbellho** [comment]
The repository name was changed today and the link has been updated.

**Comment by chrisjlocke** [comment]
Aah, I was just too quick.
Excellent, thanks!
