### ISSUE TITLE
Admin hooks page error

### ISSUE THREAD

**Issue by Piernas** [CE-PhoenixCart/PhoenixCart#28]
getting this error on admin hooks page:

Fatal error: Uncaught TypeError: get_class_vars(): Argument #1 ($class) must be a valid class name, hook_admin_system__01_href_link given

Blank install, 1.0.8.14

**Comment by ecartz** [comment]
I do not get this.  Closing, no repro.

**Comment by Piernas** [comment]
Tested latest files and the error persists but in a different hook- just to let you know:

Fatal error: Uncaught TypeError: get_class_vars(): Argument #1 ($class) must be a valid class name, cart given in E:\PhoenixCart-1.0.8.17\admin\modules_hooks.php:133 Stack trace: #0 E:\PhoenixCart-1.0.8.17\admin\modules_hooks.php(133): get_class_vars('cart') #1 {main} thrown in E:\PhoenixCart-1.0.8.17\admin\modules_hooks.php on line 133
