### ISSUE TITLE
strftime error in admin 

### ISSUE THREAD

**Issue by scottcwilson** [CE-PhoenixCart/PhoenixCart#36]
PHP 8.1, Phoenix v1.0.8.20.

To dup, go to Admin > Tools > Define Languages

```
[29-Mar-2023 12:36:19 America/New_York] PHP Deprecated:  Function strftime() is deprecated in /Users/scott/sites/phoenix_108/admin/define_language.php on line 31
```

I'm happy to PR if approved.

**Comment by ecartz** [comment]
What are you thinking?  I vaguely recall that the last time that I looked at this, there wasn't a backwardly compatible way to handle this.  So every language definition would have to switch from `strftime` to something else.  Also, there was a localization issue.  The replacement for `strftime` that is localized (`IntlDateFormatter`) is not always available.  So we would need to do one of 

1.  Require a module that not everyone will need.
2.  Drop localized time and handle that in some other way.  
3.  Or make a compatibility class that sometimes calls `IntlDateFormatter` (if available), sometimes calls `strftime` (before 8.1), and sometimes calls the non-localized replacement (`DateTime`).  And somehow handles the fact that they take different inputs.

Sorry, it's been a while, and I didn't remember the names of `IntlDateFormatter` and `DateTime`.  I had to look them up again.  I've been somewhat hoping that PHP would come up with a better fix.  For example, a `strftime` compatibility class that would do all of those things.  This was probably the biggest blocker for 8.1 when I was reading about it.  Thanks for reminding me.  

Anyway, did you have a specific solution in mind?  Or were you just thinking that of course they would have some reasonable solution?  I was thinking that before I looked at it last.  But then I stopped working on it in sheer disgust.  I mean, if they want to deprecate the always available `strftime`, they could at least make the localized replacement part of core.

**Comment by gburton** [comment]
There is this; https://github.com/alphp/strftime
Which may be a usable replacement if it starts causing major issues in Phoenix.

**Comment by ecartz** [comment]
That uses` IntlDateFormatter` under the hood.  So it won't always work.  On the bright side, it already has the `strftime` formats mapped.  So a version that worked with `DateTime` would seem possible.  I somewhat think that rather than using it as is, it would be better to wire in a similar feature where it calls `IntlDateFormatter` or `DateTime` depending on what's available.  And not call anything named `strftime`, at least on versions 8.1+.

**Comment by ecartz** [comment]
I think that this might be a better solution:  https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Intl/DateFormatter/IntlDateFormatter.php

We could throw that and its dependencies in (e.g.) system/versioned/1.0.9.2 and be able to use it if IntlDateFormatter is not found.  Then we just need to change our date handling to use IntlDateFormatter instead of strftime.

**Comment by osc2nuke** [comment]
> I think that this might be a better solution: https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Intl/DateFormatter/IntlDateFormatter.php
> 
> We could throw that and its dependencies in (e.g.) system/versioned/1.0.9.2 and be able to use it if IntlDateFormatter is not found. Then we just need to change our date handling to use IntlDateFormatter instead of strftime.

You are missing the point of versioning the core script, you should program on the core, and any other "module/add-on" that a user/client has installed should be notified that it could break their system if they chosen to do do an upgrade anyway( you can even provide a reverse back system to downgrade back)
I made all that years ago for oscompose.com ... ask Gary.
And i got the inspiration back then from @haraldpdl himself.
In theory that is how Wordpress handles "stuff"
So any module/add-on creator should be restricted to that principle.
I was at a point that whenever a creator uploaded or updated a module/add-on to the oscompose store, it had to go over a checklist to be accepted over the given credentials/specs.
If you are a core developer you are NOT responsible for modules made by 3th party.

**Comment by osc2nuke** [comment]
> What are you thinking?

That your arrogance overrules the dispute.
