### ISSUE TITLE
Fresh install "problem importing the database"

### ISSUE THREAD

**Issue by rwaters71** [CE-PhoenixCart/PhoenixCart#38]
I encountered this issue while installing the latest Phoenix cart 1.0.8.20 today...
Created an empty database and user on the server, uploaded all files, changed permissions on configure files, and started install. It got stuck on
`
There was a problem importing the database. The following error had occured:
Please verify the connection parameters and try again.
`
The web install did not provide much relevant info about the error. I am using localhost, the username/database are correct. Tried recreating the database, different username, etc, no no avail. (If user had the wrong privileges then web page provided a different, more informative warning)

There were a couple of notices/warnings in the PHP log:
`
[10-Sep-2023 21:31:52 US/Eastern] PHP Notice:  Undefined property: sql_file::$errno in /storetest/includes/system/versioned/1.0.8.9/sql_file.php on line 92
[10-Sep-2023 21:31:52 US/Eastern] PHP Notice:  Undefined property: sql_file::$error in /storetest/includes/system/versioned/1.0.8.9/sql_file.php on line 92
[10-Sep-2023 21:31:52 US/Eastern] PHP Warning:  DB: []  from </storetest/install/phoenix.sql> in /storetest/includes/system/versioned/1.0.8.9/sql_file.php on line 93
[10-Sep-2023 21:31:52 US/Eastern] PHP Notice:  Undefined variable: db_error in /storetest/install/rpc.php on line 89
`
Tried importing the referenced phoenix.sql using PhpMyAdmin, and got an error, only when creating the "auction_recorder" table (other tables are created ok):

`#1071 - Specified key was too long; max key length is 1000 bytes`

That server is using PHP 7.4.26, MariaDB 10.4.20,   default_storage_engine variable is MyIsam

Not sure if users can be expected to find or fix such SQL error easily without help/info about it on the install page? 
Also, I don't remember having that key issue with the auctions_recorder table with older installs?

**Comment by ecartz** [comment]
Change from MyIsam to InnoDB.  

This started when we changed from UTF8 to UTF8MB4.  That makes a VARCHAR(255) take 1020 bytes, which is longer than the 1000 byte limit (see the error).  If you switch to InnoDB, the limit goes up to something greater than 1000 bytes.  

Alternately, you can go through and change the affected columns to be VARCHAR(250) instead.  There's a list of the columns at https://phoenixcart.org/forum/viewtopic.php?p=3853#p3853

That says to change to 191, but that's for older versions of MySQL.  For 10.4, 250 would be sufficient with MyIsam.  But again, InnoDB is recommended.

**Comment by rwaters71** [comment]
Thank you for the clarification. I thought it may improve user experience to be able to see SQL errors on the install page in general, and maybe make the action_recorder table columns slightly shorter to be more compatible with MyIsam, just a thought.
