### ISSUE TITLE
undefined $other_img_indicator if only the main image is used

### ISSUE THREAD

**Issue by raiwa** [CE-PhoenixCart/PhoenixCart#4]
in includes/modules/content/product_info/templates/tpl_cm_pi_gallery.php
Line 25 should be moved up to line 13 (like it is done already in the pi module):
`  // now create the thumbs
  $other_img_indicator = $other_img = '';
  if (count($other_images) > 0) {
`

**Comment by ecartz** [comment]
What exactly does the notice say?

**Comment by raiwa** [comment]
Sorry, false alarm. I concluded this comparing with the pi module where it is moved up , but without testing. Just close please.
