### ISSUE TITLE
Error in create_account.php 

### ISSUE THREAD

**Issue by maxi032** [CE-PhoenixCart/PhoenixCart#42]
I've just installed locally Phoenix cart v1.0.9.0. I am using Laragon on windows 11 and php7.4 
The error is Fatal error: Uncaught TypeError: Argument 1 passed to Text::input() must be of the type string, null given, called in C:\laragon\www\catalogph9\includes\modules\customer_data\cd_country.php on line 148 and defined in C:\laragon\www\catalogph9\includes\system\versioned\1.0.8.2\text.php:34 Stack trace: #0 C:\laragon\www\catalogph9\includes\modules\customer_data\cd_country.php(148): Text::input(NULL) #1 C:\laragon\www\catalogph9\includes\system\versioned\1.0.5.6\requirements_manager.php(37): cd_country->process(Array) #2 C:\laragon\www\catalogph9\includes\system\versioned\1.0.5.6\requirements_manager.php(65): requirements_manager->act_on(Object(cd_country), 'process', Array) #3 C:\laragon\www\catalogph9\create_account.php(23): requirements_manager->process(Array) #4 {main} thrown in C:\laragon\www\catalogph9\includes\system\versioned\1.0.8.2\text.php on line 34

The error happens after I add products into the cart and proceed to creating an account. I hope you can help me

**Comment by ecartz** [comment]
Are you selecting a country from the drop down?

**Comment by maxi032** [comment]
@ecartz I don't get to that point as the dropdown is most likely in create_account.php itself

**Comment by maxi032** [comment]
For some reason the registration form is missing from my create_account.php 
![Screenshot 2024-04-02 211335](https://github.com/CE-PhoenixCart/PhoenixCart/assets/1525885/9a396afb-bc13-4c47-97f4-eb2983aaa13d)

**Comment by gburton** [comment]
Make sure you have Customer Data Groups correctly set up:
https://phoenixcart.org/phoenixcartwiki/index.php?title=Customer_Data_Groups

And make sure you have Customer Data modules correctly set up:
https://phoenixcart.org/phoenixcartwiki/index.php?title=Customer_Data

If necessary, try turning modules off and on again to see if the display problem is resolved.

**Comment by maxi032** [comment]
@gburton  Indeed reinstalling the customer data modules solved the problem. Thanks!
