### ISSUE TITLE
[Edit] Customer

### ISSUE THREAD

**Issue by MyGamesStore** [CE-PhoenixCart/PhoenixCart#9]
1.0.8.5 as at 11 June patch fbfa4e5 2 days ago Git stats 2,808 commits.

If you edit a customer it returns as if 'Are you sure you want to delete this customer?'

**Comment by ecartz** [comment]
TY.  https://github.com/CE-PhoenixCart/PhoenixCart/commit/f51125209743d3e67b59852b530769187a3fbe6b

**Comment by MyGamesStore** [comment]
Still facing a blank [EDIT] customers page. New pull from f511252.
Some errors from the log for you to help.

AH01071: Got error 'PHP message: PHP Notice:  Constant MODULES_ADMIN_MENU_CATALOG_PRODUCTS already defined in /admin/includes/languages/english/modules/boxes/catalog_categories.php on line 13', referer: https://www.MYWEBSITE.com.au/admin/customers.php

AH01071: Got error 'PHP message: PHP Deprecated:  The retain_parameters method has been deprecated. in /includes/system/versioned/1.0.8.5/href.php on line 79PHP message: PHP Deprecated:  The retain_parameters method has been deprecated. in /includes/system/versioned/1.0.8.5/href.php on line 79PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Form::hide() must be of the type string, null given, called in /admin/customers.php on line 56 and defined in /includes/system/versioned/1.0.8.1/form.php:73\nStack trace:\n#0 /admin/customers.php(56): Form->hide()\n#1 {main}\n  thrown in /includes/system/versioned/1.0.8.1/form.php on line 73', referer: https://www.MYWEBSITE.com.au/admin/customers.php

Mark.

**Comment by MyGamesStore** [comment]
line 63 is incomplete.
$customer_data_group_query = $db->query(sprintf(<<<'EOSQL'
